export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

